### ISSUE TITLE
I just don't understand

### ISSUE THREAD

**Issue by Luomin1993** [BruceSherwood/vpython-wx#83]
When the module is called "visual" it's a lib easy to use,
Now,it's a strange lib with errors!!!
 I just don't understand why you just make it has to be used in note-book,no-one wants to!!!!!!
How can I use it by simply "python demo.py" under Linux?????

**Comment by BruceSherwood** [comment]
See vpython.org. You can certainly run "python demo.py" in Linux after installing the vpython module as explained at vpython.org. As for why we had to stop support of visual in January 2016, see this: 

http://vpython.org/contents/announcements/evolution.html

**Comment by BruceSherwood** [comment]
Now I see where the confusion came from. This README had not been updated to refer to VPython 7, which runs with installed Python 2.7 or Python 3.x, inside or outside a Jupyter notebook.
